# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-11-09 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('rx', models.CharField(max_length=30, verbose_name='RX')),
                ('invst_type', models.CharField(max_length=10, verbose_name='Type')),
                ('amount', models.FloatField(verbose_name='Amount')),
                ('mat', models.FloatField(blank=True, null=True, verbose_name='Maturity')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('roi', models.FloatField(blank=True, null=True, verbose_name='RoI')),
                ('months', models.IntegerField(blank=True, null=True, verbose_name='Months')),
                ('roiYear', models.FloatField(blank=True, null=True, verbose_name='Roi/Year')),
            ],
            options={
                'verbose_name': 'Investments',
                'ordering': ['date'],
            },
        ),
    ]
