# Generated by Django 2.0.3 on 2019-12-15 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invst', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('rx', models.CharField(max_length=30, verbose_name='RX')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Amount')),
            ],
            options={
                'verbose_name': 'Dental',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='MF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('planName', models.CharField(max_length=90, verbose_name='Plan Name')),
                ('platform', models.CharField(max_length=10, verbose_name='Platform')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Amount')),
                ('lockin', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Lock-In')),
            ],
            options={
                'verbose_name': 'Mutual Funds',
                'ordering': ['date'],
            },
        ),
        migrations.AlterModelOptions(
            name='invst',
            options={'ordering': ['date'], 'verbose_name': 'Investment'},
        ),
        migrations.AlterField(
            model_name='invst',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='invst',
            name='mat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Maturity'),
        ),
    ]
